### ISSUE TITLE
Parallel testing

### ISSUE THREAD

**Issue by raszi** [bdelespierre/laravel-blade-linter#3]
We are running your linter in our CI pipeline to filter out issues in the blade templates. It helps to reduce production issues by catching issues early, thank you for that!

Since we have a couple of linters, static analysers and the tests of course, the pipeline takes a long time to finish. `phplint`, `phpcs` and even `phpunit` supports parallel runs in some way it would be great if we could also benefit from the available cores by running the blade linter in parallel.

Are there any plans to introduce parallel testing to this project?

Thanks!

**Comment by bdelespierre** [comment]
Sorry for the late answer. Glad you're using my linter :+1: 

I currently have no plan for making parallel tests but here's how you can do it with `xargs` command:

```BASH
find resources/views/ -type f -name '*.blade.php' -print0 | xargs -0  -n1 -P8 php artisan blade:lint
```

Replace `-P8` by the number of cores you have e.g. `-P16` :smile:

**Comment by raszi** [comment]
Thank you @bdelespierre that is a good workaround for now.

**Comment by raszi** [comment]
Actually the provided solution isn't good as it is since it will invoke `php artisan blade:lint` with only one parameter and there will be a lot of overhead on the command execution.

**Comment by bdelespierre** [comment]
In that case, change the `-n1` parameter to `-n50` for instance to process by bulks of 50.

From the xargs man page:
```
       -n max-args, --max-args=max-args
              Use at most max-args arguments per command line.  Fewer than max-args arguments will be used if the size (see the -s option) is exceeded, unless the -x option is given, in which case xargs will
              exit.
```

**Comment by raszi** [comment]
Yes, I know I can set the maximum parameters to the processes and that is what I ended up with (100 per process).

I am thinking of opening a PR with the required changes to make your project parallel.

**Comment by bdelespierre** [comment]
Sure go ahead :+1: All PR are welcome.
