### ISSUE TITLE
[Question] About the standalone "laravel-blade-linter"

### ISSUE THREAD

**Issue by yaegassy** [bdelespierre/laravel-blade-linter#7]
I used "laravel-blade-linter" to create a plugin (extension) that works with "Vim" (coc.nvim ). 🙇

- <https://github.com/yaegassy/coc-blade-linter>

"laravel-blade-linter" is a command that is added to `artisan`, are there any plans for a standalone tool? (Distribute with phar?)

**Comment by bdelespierre** [comment]
Since it was intended to be a Laravel package, I didn't plan to package it with phar. 

It's an interesting idea though, technically it could run autonomously with a few adjustments.

Would you be interested in making it happen?

**Comment by yaegassy** [comment]
Of course, I'm interested.

I asked this question because I thought it would be more convenient to be able to use it without worrying about project dependencies.

This issue is closed.

Thanks for the reply. 🙇

**Comment by bdelespierre** [comment]
You know what @yaegassy ? I did it.

https://github.com/bdelespierre/laravel-blade-linter/blob/master/laravel-blade-linter.phar

Have fun.

**Comment by bdelespierre** [comment]
Thanks for giving me the opportunity to learn something @yaegassy :+1:

**Comment by yaegassy** [comment]
Great!!

As for the name of the phar file, I thought it would be better if it were shorter. (e.g. `blade-linter.phar`)

It seems to be possible to change more than just the project name with `phar-composer`. (`php-composer build [project] [target]`)

```sh
$ phar-composer build . blade-linter
```

If @bdelespierre prefers the same name as the project name, no problem.

---

Now, with phar in the root of the repository, run `phar-composer build` in the same way again, and the size of phar will double. (current: "16MB" -> next: 32MB)

This may be a good point to keep in mind when updating.

For example, it may be a good idea to add a phar file to "GitHub release" when upgrading. e.g. [clue/phar-composer/releases](https://github.com/clue/phar-composer/releases)

**Comment by bdelespierre** [comment]
I'll look into it

**Comment by yaegassy** [comment]
@bdelespierre Sorry about that. The file size (`16MB`) in this comment is the size of the file created with --no-dev in my environment. I'm sorry if I've confused you.

However, the current phar file size in the repository is `61MB`. (More big...).

```
laravel-blade-linter$ ls -lah
total 124912
// ...snip
-rwxr-xr-x   1 yaegassy  staff    61M  4 19 15:54 laravel-blade-linter.phar
// ...snip
```

When I installed with `--no-dev`, the file size was `16MB`. If you have no problem with `--no-dev`, it's better.

```
rm laravel-blade-linter.phar
composer install --no-dev 
phar-composer build ./
```

---

```
laravel-blade-linter$ ls -lah
total 32840
// ...snip
-rwxr-xr-x   1 yaegassy  staff    16M  4 19 15:58 laravel-blade-linter.phar
// ...snip
```

**Comment by yaegassy** [comment]
@bdelespierre As an additional report, it seems that 60MB of phar is included even when installing with composer.

```sh
$ composer require --dev bdelespierre/laravel-blade-linter
$ # ...snip
$ ls -alh vendor/bdelespierre/laravel-blade-linter/laravel-blade-linter.phar
-rwxr-xr-x  1 yaegassy  staff    61M  4 16 18:11 vendor/bdelespierre/laravel-blade-linter/laravel-blade-linter.phar
```

You may want to remove the phar file from the repository and upload it to GitHub release.

**Comment by bdelespierre** [comment]
@yaegassy Yes. I think it's doing more harm than good. to have the .phar laying around like this. Haven't had time to look into it yesterday, I'll get to it tonight.

**Comment by bdelespierre** [comment]
@yaegassy sorry for the late response. Here is your release : https://github.com/bdelespierre/laravel-blade-linter/releases/tag/v1.6.0

- The .phar archive is now removed from master, you can install using composer without downloading it
- The .phar archive size has been reduced to 17MB
- *.phar has been added to .gitignore and the README.md has been updated with new building instructions

Thanks a lot for your contribution :+1:
