### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by williamdes** [bdelespierre/laravel-blade-linter#9]
If this project is dead, maybe archive it.

I can see two forks active, but no PRs:
- https://github.com/jbboehr/laravel-blade-linter: https://github.com/bdelespierre/laravel-blade-linter/compare/master...jbboehr:laravel-blade-linter:master (packagist ready)
- https://github.com/superbiche/laravel-blade-linter/commit/b8b7e544cfcc7b2a12f3ee1499c09f05b44a8536 (only one commit)

cc @jbboehr & @superbiche

**Comment by bdelespierre** [comment]
Thanks for the heads up, I'm on it

**Comment by bdelespierre** [comment]
Okay done!

**Comment by jbboehr** [comment]
We wound up not using my fork at work and just running `artisan view:cache && find -name '*.blade.php' | xargs -p -n1 php -l` in CI.

IIRC latest PHP now supports multiple files with `php -l` so should be even faster.

**Comment by jbboehr** [comment]
The main reason I wanted to use this package was to stuff the results into Gitlab's [Code Quality Reports](https://docs.gitlab.com/ee/ci/testing/code_quality.html), which is why there's a docker image and codeclimate output format in my fork.

**Comment by williamdes** [comment]
Thank you for merging the upstream work, I guess it means that this project is still alive
Are contributions welcome before a new release is drafted?

**Comment by bdelespierre** [comment]
I'm not actively working on it but I'll merge any PR that makes sense :dancers:

**Comment by bdelespierre** [comment]
I should do a new release after merging the code from @jbboehr

**Comment by williamdes** [comment]
> I should do a new release after merging the code from @jbboehr

Well, I have no idea of what I wanted to contribute. But I tested the latest commit and it works fine
Can you push a tag please ?

**Comment by bdelespierre** [comment]
New release v1.7.0 is available
